// components/About.tsx
"use client";

import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Heart, Download, Check } from "lucide-react";
import { getCurrentWebviewWindow } from "@tauri-apps/api/webviewWindow";
import { getVersion } from "@tauri-apps/api/app";
import { check as checkForUpdate } from "@tauri-apps/plugin-updater";
import { relaunch } from "@tauri-apps/plugin-process";
import { CustomTitleBar } from "@/components/CustomTitleBar";
import { open } from "@tauri-apps/plugin-shell";

// Lucide removed brand icons (incl. GitHub) in v1 for trademark reasons.
function GithubIcon({ className }: { className?: string }) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      className={className}
      aria-hidden="true"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.4 5.4 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

type UpdateStatus =
  | { kind: "idle" }
  | { kind: "checking" }
  | { kind: "uptodate" }
  | { kind: "available"; version: string }
  | { kind: "installing" }
  | { kind: "error"; message: string };

export function About() {
  const [version, setVersion] = useState<string>("…");
  const [updateStatus, setUpdateStatus] = useState<UpdateStatus>({ kind: "idle" });

  useEffect(() => {
    getVersion().then(setVersion).catch(() => setVersion("unknown"));
  }, []);

  const handleClose = async () => {
    const w = getCurrentWebviewWindow();
    await w.close();
  };

  async function handleCheckForUpdates() {
    setUpdateStatus({ kind: "checking" });
    try {
      const update = await checkForUpdate();
      if (update) {
        setUpdateStatus({ kind: "available", version: update.version });
      } else {
        setUpdateStatus({ kind: "uptodate" });
      }
    } catch (err) {
      setUpdateStatus({
        kind: "error",
        message: err instanceof Error ? err.message : "Update check failed",
      });
    }
  }

  async function handleInstallUpdate() {
    setUpdateStatus({ kind: "installing" });
    try {
      const update = await checkForUpdate();
      if (update) {
        await update.downloadAndInstall();
        await relaunch();
      }
    } catch (err) {
      setUpdateStatus({
        kind: "error",
        message: err instanceof Error ? err.message : "Update install failed",
      });
    }
  }

  return (
    <div className="flex h-screen w-full flex-col">
      <CustomTitleBar title="About" hideMaximize={true} />

      <ScrollArea className="flex-1">
        <div className="flex flex-col items-center justify-center p-12 space-y-8">
          {/* App Icon and Title */}
          <div className="flex flex-col items-center space-y-4">
            <img
              src="/app-icon.png"
              alt="App Icon"
              className="h-24 w-24"
            />
            <div className="text-center space-y-2">
              <h1 className="text-3xl font-bold tracking-tight">
                Simple Password Manager
              </h1>
              <p className="text-sm text-muted-foreground">
                Version {version}
              </p>
            </div>
          </div>

          {/* Description */}
          <p className="text-center text-muted-foreground max-w-md leading-relaxed">
            A secure and modern password manager built with the proven KeePass
            database format. Keep your passwords safe with strong encryption.
          </p>

          {/* Update card */}
          <UpdateCard
            status={updateStatus}
            onCheck={handleCheckForUpdates}
            onInstall={handleInstallUpdate}
          />

          {/* Links */}
          <div className="flex flex-col gap-3 w-full max-w-xs">
            <Button
              variant="outline"
              className="w-full justify-center gap-2"
              onClick={() =>
                open("https://github.com/jonax1337/Simple-Password-Manager")
              }
            >
              <GithubIcon className="h-4 w-4" />
              View on GitHub
            </Button>
          </div>

          {/* Tech Stack - Simple badges */}
          <div className="flex flex-wrap justify-center gap-2 mt-4">
            <span className="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">
              Tauri
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">
              React
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">
              Next.js
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">
              Rust
            </span>
            <span className="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">
              TypeScript
            </span>
          </div>

          {/* Footer */}
          <div className="pt-8 text-center space-y-1">
            <p className="text-xs text-muted-foreground flex items-center justify-center gap-1">
              Made with <Heart className="h-3 w-3 fill-current text-red-500" /> by
              Jonas Laux
            </p>
            <p className="text-xs text-muted-foreground">
              Open Source • MIT License
            </p>
          </div>
        </div>
      </ScrollArea>
      <button hidden onClick={handleClose} />
    </div>
  );
}

function UpdateCard(props: {
  status: UpdateStatus;
  onCheck: () => void;
  onInstall: () => void;
}) {
  const busy = props.status.kind === "checking" || props.status.kind === "installing";

  return (
    <div className="w-full max-w-xs rounded-md border p-3">
      <div className="flex items-center gap-2.5">
        {props.status.kind === "uptodate" ? (
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-emerald-500/15">
            <Check className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />
          </div>
        ) : (
          <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
            <Download className="h-3.5 w-3.5 text-primary" />
          </div>
        )}
        <div className="min-w-0 flex-1 text-sm">
          {props.status.kind === "idle" && (
            <span className="text-muted-foreground">
              Check if a newer version is available.
            </span>
          )}
          {props.status.kind === "checking" && (
            <span className="text-muted-foreground">Checking for updates…</span>
          )}
          {props.status.kind === "uptodate" && (
            <span>You&apos;re on the latest version.</span>
          )}
          {props.status.kind === "available" && (
            <span>
              <span className="font-medium">{props.status.version}</span> is
              ready to install.
            </span>
          )}
          {props.status.kind === "installing" && (
            <span className="text-muted-foreground">
              Downloading and installing…
            </span>
          )}
          {props.status.kind === "error" && (
            <span className="text-destructive text-xs">
              {props.status.message}
            </span>
          )}
        </div>
      </div>
      <div className="mt-3 flex gap-2">
        {props.status.kind === "available" ? (
          <Button
            size="sm"
            className="flex-1"
            onClick={props.onInstall}
            disabled={busy}
          >
            Install &amp; restart
          </Button>
        ) : (
          <Button
            size="sm"
            variant="outline"
            className="flex-1"
            onClick={props.onCheck}
            disabled={busy}
          >
            {props.status.kind === "checking" ? "Checking…" : "Check for updates"}
          </Button>
        )}
      </div>
    </div>
  );
}

// src/routes/About.svelte
<script lang="ts">
  import { Button } from "$lib/ui";
  import { Heart, Download, Check, ArrowLeft } from "@lucide/svelte";
  import { onMount } from "svelte";
  import { getVersion } from "@tauri-apps/api/app";
  import { check as checkForUpdate } from "@tauri-apps/plugin-updater";
  import { relaunch } from "@tauri-apps/plugin-process";
  import { open as openShell } from "@tauri-apps/plugin-shell";
  import { pop } from "svelte-spa-router";

  type Status =
    | { kind: "idle" }
    | { kind: "checking" }
    | { kind: "uptodate" }
    | { kind: "available"; version: string }
    | { kind: "installing" }
    | { kind: "error"; message: string };

  let version = $state("…");
  let status = $state<Status>({ kind: "idle" });

  onMount(() => {
    getVersion().then((v) => (version = v)).catch(() => (version = "unknown"));
  });

  const busy = $derived(status.kind === "checking" || status.kind === "installing");

  async function check() {
    status = { kind: "checking" };
    try {
      const u = await checkForUpdate();
      if (u) status = { kind: "available", version: u.version };
      else status = { kind: "uptodate" };
    } catch (e) {
      status = { kind: "error", message: e instanceof Error ? e.message : "Update check failed" };
    }
  }

  async function install() {
    status = { kind: "installing" };
    try {
      const u = await checkForUpdate();
      if (u) {
        await u.downloadAndInstall();
        await relaunch();
      }
    } catch (e) {
      status = { kind: "error", message: e instanceof Error ? e.message : "Install failed" };
    }
  }
</script>

<div class="flex h-full flex-col">
  <div class="shrink-0 flex items-center gap-2 border-b px-4 py-3">
    <Button variant="ghost" size="icon" onclick={() => pop()}>
      <ArrowLeft class="h-4 w-4" />
    </Button>
    <h1 class="text-lg font-semibold">About</h1>
  </div>

  <div class="flex-1 overflow-auto">
    <div class="flex flex-col items-center justify-center p-12 space-y-8">
      <div class="flex flex-col items-center space-y-4">
        <img src="/app-icon.png" alt="App Icon" class="h-24 w-24 drop-shadow-md" />
        <div class="text-center space-y-2">
          <h1 class="text-3xl font-bold tracking-tight">Simple Password Manager</h1>
          <p class="text-sm text-muted-foreground">Version {version}</p>
        </div>
      </div>

      <p class="text-center text-muted-foreground max-w-md leading-relaxed">
        A secure and modern password manager built with the proven KeePass database format. Keep your
        passwords safe with strong encryption.
      </p>

      <div class="w-full max-w-xs rounded-md border p-3">
        <div class="flex items-center gap-2.5">
          {#if status.kind === "uptodate"}
            <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-success/15">
              <Check class="h-3.5 w-3.5 text-success" />
            </div>
          {:else}
            <div class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary/10">
              <Download class="h-3.5 w-3.5 text-primary" />
            </div>
          {/if}
          <div class="min-w-0 flex-1 text-sm">
            {#if status.kind === "idle"}
              <span class="text-muted-foreground">Check if a newer version is available.</span>
            {:else if status.kind === "checking"}
              <span class="text-muted-foreground">Checking for updates…</span>
            {:else if status.kind === "uptodate"}
              <span>You're on the latest version.</span>
            {:else if status.kind === "available"}
              <span><span class="font-medium">{status.version}</span> is ready to install.</span>
            {:else if status.kind === "installing"}
              <span class="text-muted-foreground">Downloading and installing…</span>
            {:else if status.kind === "error"}
              <span class="text-destructive text-xs">{status.message}</span>
            {/if}
          </div>
        </div>
        <div class="mt-3 flex gap-2">
          {#if status.kind === "available"}
            <Button size="sm" class="flex-1" onclick={install} disabled={busy}>
              Install &amp; restart
            </Button>
          {:else}
            <Button size="sm" variant="outline" class="flex-1" onclick={check} disabled={busy}>
              {status.kind === "checking" ? "Checking…" : "Check for updates"}
            </Button>
          {/if}
        </div>
      </div>

      <div class="flex flex-col gap-3 w-full max-w-xs">
        <Button variant="outline" class="w-full justify-center gap-2" onclick={() => openShell("https://github.com/jonax1337/Simple-Password-Manager")}>
          View on GitHub
        </Button>
      </div>

      <div class="flex flex-wrap justify-center gap-2 mt-4">
        {#each ["Tauri", "Svelte 5", "Vite", "Rust", "TypeScript"] as t (t)}
          <span class="text-xs px-3 py-1 rounded-full bg-secondary text-secondary-foreground">{t}</span>
        {/each}
      </div>

      <div class="pt-8 text-center space-y-1">
        <p class="text-xs text-muted-foreground flex items-center justify-center gap-1">
          Made with <Heart class="h-3 w-3 fill-current text-destructive" /> by Jonas Laux
        </p>
        <p class="text-xs text-muted-foreground">Open Source • MIT License</p>
      </div>
    </div>
  </div>
</div>
