// components/Dashboard.tsx
"use client";

import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getDashboardStats } from "@/lib/tauri";
import type { DashboardStats } from "@/lib/tauri";
import { 
  Shield, 
  Key, 
  AlertTriangle, 
  Clock, 
  Star, 
  FolderTree,
  TrendingUp,
  Copy
} from "lucide-react";
import { useToast } from "@/components/ui/use-toast";
import { BreachedPasswordsCard } from "@/components/BreachedPasswordsCard";
import { getEntry } from "@/lib/tauri";
import { getHibpEnabled } from "@/lib/storage";
import { openEntryWindow } from "@/lib/window";

interface DashboardProps {
  refreshTrigger?: number;
  databasePath?: string;
  isDirty?: boolean;
}

export function Dashboard({ refreshTrigger, databasePath, isDirty }: DashboardProps) {
  const [stats, setStats] = useState<DashboardStats | null>(null);
  const [hibpEnabled, setHibpEnabled] = useState<boolean>(false);
  const { toast } = useToast();

  useEffect(() => {
    setHibpEnabled(getHibpEnabled());
  }, []);

  const handleEditEntry = async (entryUuid: string) => {
    try {
      const entry = await getEntry(entryUuid);
      await openEntryWindow(entry, entry.group_uuid);
    } catch (error: any) {
      toast({
        title: "Error",
        description: typeof error === 'string' ? error : (error?.message || "Failed to open entry"),
        variant: "destructive",
      });
    }
  };

  useEffect(() => {
    loadStats();
  }, [refreshTrigger]);

  const loadStats = async () => {
    try {
      const data = await getDashboardStats();
      setStats(data);
    } catch (error: any) {
      toast({
        title: "Error",
        description: error?.message || "Failed to load dashboard statistics",
        variant: "destructive",
      });
    }
  };

  const getStrengthLevel = (bits: number): { label: string; color: string } => {
    if (bits < 40) return { label: "Weak", color: "text-red-500" };
    if (bits < 64) return { label: "Fair", color: "text-orange-500" };
    if (bits < 80) return { label: "Good", color: "text-yellow-500" };
    if (bits < 112) return { label: "Strong", color: "text-blue-500" };
    return { label: "Excellent", color: "text-green-500" };
  };

  const strengthInfo = stats ? getStrengthLevel(stats.average_password_strength) : { label: "...", color: "text-muted-foreground" };
  const healthScore = stats ? Math.max(
    0,
    100 - 
    (stats.weak_passwords / Math.max(stats.total_entries, 1)) * 30 -
    (stats.reused_passwords / Math.max(stats.total_entries, 1)) * 25 -
    (stats.old_passwords / Math.max(stats.total_entries, 1)) * 20 -
    (stats.expired_entries / Math.max(stats.total_entries, 1)) * 25
  ) : 0;

  const fadeInUp = {
    initial: { opacity: 0, y: 20 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.4, ease: "easeOut" }
  };

  const staggerContainer = {
    animate: {
      transition: {
        staggerChildren: 0.1
      }
    }
  };

  return (
    <div className="h-full overflow-auto">
      <div className="space-y-4 p-4">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4, ease: "easeOut" }}
        >
          <h1 className="text-3xl font-bold tracking-tight">Dashboard</h1>
          <p className="text-muted-foreground mt-1">
            Overview of your password database health and statistics
          </p>
        </motion.div>

        {hibpEnabled && (
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut", delay: 0.1 }}
          >
            <BreachedPasswordsCard
              refreshTrigger={refreshTrigger}
              databasePath={databasePath}
              onEditEntry={handleEditEntry}
              isDirty={isDirty}
            />
          </motion.div>
        )}

        <motion.div 
          className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"
          variants={staggerContainer}
          initial="initial"
          animate="animate"
        >
          <motion.div variants={fadeInUp}>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Total Entries</CardTitle>
                <Key className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{stats?.total_entries ?? "..."}</div>
                <p className="text-xs text-muted-foreground mt-1">
                  Across {stats?.total_groups ?? "..."} groups
                </p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div variants={fadeInUp}>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Health Score</CardTitle>
                <Shield className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{stats ? Math.round(healthScore) : "..."}%</div>
                <p className="text-xs text-muted-foreground mt-1">
                  Database security rating
                </p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div variants={fadeInUp}>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Avg. Strength</CardTitle>
                <TrendingUp className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className={`text-2xl font-bold ${strengthInfo.color}`}>
                  {strengthInfo.label}
                </div>
                <p className="text-xs text-muted-foreground mt-1">
                  {stats ? Math.round(stats.average_password_strength) : "..."} bits entropy
                </p>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div variants={fadeInUp}>
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">Favorites</CardTitle>
                <Star className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{stats?.favorite_entries ?? "..."}</div>
                <p className="text-xs text-muted-foreground mt-1">
                  Marked as favorite
                </p>
              </CardContent>
            </Card>
          </motion.div>
        </motion.div>

        <motion.div 
          className="grid gap-4 md:grid-cols-2"
          variants={staggerContainer}
          initial="initial"
          animate="animate"
        >
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut", delay: 0.5 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Security Issues</CardTitle>
                <CardDescription>
                  Passwords that need attention
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4 text-red-500" />
                    <span className="text-sm font-medium">Weak Passwords</span>
                  </div>
                  <span className={`text-lg font-bold ${stats && stats.weak_passwords > 0 ? 'text-red-500' : 'text-green-500'}`}>
                    {stats?.weak_passwords ?? "..."}
                  </span>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Copy className="h-4 w-4 text-orange-500" />
                    <span className="text-sm font-medium">Reused Passwords</span>
                  </div>
                  <span className={`text-lg font-bold ${stats && stats.reused_passwords > 0 ? 'text-orange-500' : 'text-green-500'}`}>
                    {stats?.reused_passwords ?? "..."}
                  </span>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Clock className="h-4 w-4 text-yellow-500" />
                    <span className="text-sm font-medium">Old Passwords</span>
                  </div>
                  <span className={`text-lg font-bold ${stats && stats.old_passwords > 0 ? 'text-yellow-500' : 'text-green-500'}`}>
                    {stats?.old_passwords ?? "..."}
                  </span>
                </div>

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <AlertTriangle className="h-4 w-4 text-red-500" />
                    <span className="text-sm font-medium">Expired Entries</span>
                  </div>
                  <span className={`text-lg font-bold ${stats && stats.expired_entries > 0 ? 'text-red-500' : 'text-green-500'}`}>
                    {stats?.expired_entries ?? "..."}
                  </span>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, ease: "easeOut", delay: 0.6 }}
          >
            <Card>
              <CardHeader>
                <CardTitle>Recommendations</CardTitle>
                <CardDescription>
                  Actions to improve your security
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                {!stats ? (
                  <div className="text-sm text-muted-foreground">Loading recommendations...</div>
                ) : stats.weak_passwords === 0 && 
                   stats.reused_passwords === 0 && 
                   stats.old_passwords === 0 && 
                   stats.expired_entries === 0 ? (
                  <div className="flex items-start gap-2 text-sm">
                    <Shield className="h-4 w-4 text-green-500 mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium text-green-600">All good!</p>
                      <p className="text-muted-foreground text-xs">
                        No security issues detected
                      </p>
                    </div>
                  </div>
                ) : (
                  <>
                {stats.weak_passwords > 0 && (
                  <div className="flex items-start gap-2 text-sm">
                    <AlertTriangle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium">Update weak passwords</p>
                      <p className="text-muted-foreground text-xs">
                        {stats.weak_passwords} password{stats.weak_passwords !== 1 ? 's' : ''} with less than 40 bits of entropy
                      </p>
                    </div>
                  </div>
                )}

                {stats.reused_passwords > 0 && (
                  <div className="flex items-start gap-2 text-sm">
                    <Copy className="h-4 w-4 text-orange-500 mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium">Replace reused passwords</p>
                      <p className="text-muted-foreground text-xs">
                        {stats.reused_passwords} password{stats.reused_passwords !== 1 ? 's are' : ' is'} used multiple times
                      </p>
                    </div>
                  </div>
                )}

                {stats.old_passwords > 0 && (
                  <div className="flex items-start gap-2 text-sm">
                    <Clock className="h-4 w-4 text-yellow-500 mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium">Refresh old passwords</p>
                      <p className="text-muted-foreground text-xs">
                        {stats.old_passwords} password{stats.old_passwords !== 1 ? 's' : ''} older than 90 days
                      </p>
                    </div>
                  </div>
                )}

                {stats.expired_entries > 0 && (
                  <div className="flex items-start gap-2 text-sm">
                    <AlertTriangle className="h-4 w-4 text-red-500 mt-0.5 shrink-0" />
                    <div>
                      <p className="font-medium">Review expired entries</p>
                      <p className="text-muted-foreground text-xs">
                        {stats.expired_entries} entr{stats.expired_entries !== 1 ? 'ies have' : 'y has'} passed expiration date
                      </p>
                    </div>
                  </div>
                )}
                  </>
                )}
              </CardContent>
            </Card>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}

// src/lib/components/Dashboard.svelte
<script lang="ts">
  import { Card, CardHeader, CardTitle, CardDescription, CardContent, toast } from "$lib/ui";
  import { Shield, Key, AlertTriangle, Clock, Star, TrendingUp, Copy } from "@lucide/svelte";
  import { getDashboardStats, type DashboardStats } from "$lib/tauri";
  import { getHibpEnabled } from "$lib/storage";
  import { appState } from "$lib/app-state.svelte";
  import BreachedPasswordsCard from "./BreachedPasswordsCard.svelte";
  import { onMount } from "svelte";

  type Props = { refreshTrigger?: number; onJumpToEntry?: (uuid: string) => void };
  let { refreshTrigger = 0, onJumpToEntry }: Props = $props();

  let hibpEnabled = $state(false);
  onMount(() => {
    hibpEnabled = getHibpEnabled();
  });

  let stats = $state<DashboardStats | null>(null);

  $effect(() => {
    void refreshTrigger;
    void load();
  });

  async function load() {
    try {
      stats = await getDashboardStats();
    } catch (e) {
      toast.error("Error", "Failed to load dashboard statistics");
    }
  }

  function strengthLabel(bits: number): { label: string; cls: string } {
    if (bits < 40) return { label: "Weak", cls: "text-destructive" };
    if (bits < 64) return { label: "Fair", cls: "text-warning" };
    if (bits < 80) return { label: "Good", cls: "text-warning" };
    if (bits < 112) return { label: "Strong", cls: "text-primary" };
    return { label: "Excellent", cls: "text-success" };
  }

  const strength = $derived(stats ? strengthLabel(stats.average_password_strength) : { label: "…", cls: "text-muted-foreground" });
  const healthScore = $derived(
    stats
      ? Math.max(
          0,
          100 -
            (stats.weak_passwords / Math.max(stats.total_entries, 1)) * 30 -
            (stats.reused_passwords / Math.max(stats.total_entries, 1)) * 25 -
            (stats.old_passwords / Math.max(stats.total_entries, 1)) * 20 -
            (stats.expired_entries / Math.max(stats.total_entries, 1)) * 25,
        )
      : 0,
  );
</script>

<div class="h-full overflow-auto">
  <div class="space-y-4 p-4">
    <div>
      <h1 class="text-3xl font-bold tracking-tight">Dashboard</h1>
      <p class="text-muted-foreground mt-1">Overview of your password database health and statistics</p>
    </div>

    {#if hibpEnabled}
      <BreachedPasswordsCard
        {refreshTrigger}
        databasePath={appState.dbPath}
        isDirty={appState.isDirty}
        {onJumpToEntry}
      />
    {/if}

    <div class="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium">Total Entries</CardTitle>
          <Key class="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div class="text-2xl font-bold">{stats?.total_entries ?? "…"}</div>
          <p class="text-xs text-muted-foreground mt-1">Across {stats?.total_groups ?? "…"} groups</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium">Health Score</CardTitle>
          <Shield class="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div class="text-2xl font-bold">{stats ? Math.round(healthScore) : "…"}%</div>
          <p class="text-xs text-muted-foreground mt-1">Database security rating</p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium">Avg. Strength</CardTitle>
          <TrendingUp class="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div class="text-2xl font-bold {strength.cls}">{strength.label}</div>
          <p class="text-xs text-muted-foreground mt-1">
            {stats ? Math.round(stats.average_password_strength) : "…"} bits entropy
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle class="text-sm font-medium">Favorites</CardTitle>
          <Star class="h-4 w-4 text-muted-foreground" />
        </CardHeader>
        <CardContent>
          <div class="text-2xl font-bold">{stats?.favorite_entries ?? "…"}</div>
          <p class="text-xs text-muted-foreground mt-1">Marked as favorite</p>
        </CardContent>
      </Card>
    </div>

    <div class="grid gap-4 md:grid-cols-2">
      <Card>
        <CardHeader>
          <CardTitle>Security Issues</CardTitle>
          <CardDescription>Passwords that need attention</CardDescription>
        </CardHeader>
        <CardContent class="space-y-4">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <AlertTriangle class="h-4 w-4 text-destructive" />
              <span class="text-sm font-medium">Weak Passwords</span>
            </div>
            <span class="text-lg font-bold {stats && stats.weak_passwords > 0 ? 'text-destructive' : 'text-success'}">
              {stats?.weak_passwords ?? "…"}
            </span>
          </div>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <Copy class="h-4 w-4 text-warning" />
              <span class="text-sm font-medium">Reused Passwords</span>
            </div>
            <span class="text-lg font-bold {stats && stats.reused_passwords > 0 ? 'text-warning' : 'text-success'}">
              {stats?.reused_passwords ?? "…"}
            </span>
          </div>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <Clock class="h-4 w-4 text-warning" />
              <span class="text-sm font-medium">Old Passwords</span>
            </div>
            <span class="text-lg font-bold {stats && stats.old_passwords > 0 ? 'text-warning' : 'text-success'}">
              {stats?.old_passwords ?? "…"}
            </span>
          </div>
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <AlertTriangle class="h-4 w-4 text-destructive" />
              <span class="text-sm font-medium">Expired Entries</span>
            </div>
            <span class="text-lg font-bold {stats && stats.expired_entries > 0 ? 'text-destructive' : 'text-success'}">
              {stats?.expired_entries ?? "…"}
            </span>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle>Recommendations</CardTitle>
          <CardDescription>Actions to improve your security</CardDescription>
        </CardHeader>
        <CardContent class="space-y-3">
          {#if !stats}
            <div class="text-sm text-muted-foreground">Loading recommendations…</div>
          {:else if stats.weak_passwords === 0 && stats.reused_passwords === 0 && stats.old_passwords === 0 && stats.expired_entries === 0}
            <div class="flex items-start gap-2 text-sm">
              <Shield class="h-4 w-4 text-success mt-0.5 shrink-0" />
              <div>
                <p class="font-medium text-success">All good!</p>
                <p class="text-muted-foreground text-xs">No security issues detected</p>
              </div>
            </div>
          {:else}
            {#if stats.weak_passwords > 0}
              <div class="flex items-start gap-2 text-sm">
                <AlertTriangle class="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                <div>
                  <p class="font-medium">Update weak passwords</p>
                  <p class="text-muted-foreground text-xs">{stats.weak_passwords} with less than 40 bits of entropy</p>
                </div>
              </div>
            {/if}
            {#if stats.reused_passwords > 0}
              <div class="flex items-start gap-2 text-sm">
                <Copy class="h-4 w-4 text-warning mt-0.5 shrink-0" />
                <div>
                  <p class="font-medium">Replace reused passwords</p>
                  <p class="text-muted-foreground text-xs">{stats.reused_passwords} used multiple times</p>
                </div>
              </div>
            {/if}
            {#if stats.old_passwords > 0}
              <div class="flex items-start gap-2 text-sm">
                <Clock class="h-4 w-4 text-warning mt-0.5 shrink-0" />
                <div>
                  <p class="font-medium">Refresh old passwords</p>
                  <p class="text-muted-foreground text-xs">{stats.old_passwords} older than 90 days</p>
                </div>
              </div>
            {/if}
            {#if stats.expired_entries > 0}
              <div class="flex items-start gap-2 text-sm">
                <AlertTriangle class="h-4 w-4 text-destructive mt-0.5 shrink-0" />
                <div>
                  <p class="font-medium">Review expired entries</p>
                  <p class="text-muted-foreground text-xs">{stats.expired_entries} past expiration</p>
                </div>
              </div>
            {/if}
          {/if}
        </CardContent>
      </Card>
    </div>
  </div>
</div>
