// components/entry-editor/TotpSection.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Check, Copy, KeyRound, Trash2 } from "lucide-react";
import { previewTotp, type TotpPreview } from "@/lib/tauri";
import type { EntryData, CustomField } from "@/lib/tauri";

interface Props {
  formData: EntryData;
  setFormData: React.Dispatch<React.SetStateAction<EntryData>>;
  setHasChanges: React.Dispatch<React.SetStateAction<boolean>>;
}

const OTP_FIELD = "otp";

export function TotpSection({ formData, setFormData, setHasChanges }: Props) {
  // The `otp` field, if it exists. We look it up by lowercased name to
  // match the bridge's case-insensitive lookup.
  const otpField = useMemo(
    () =>
      (formData.custom_fields ?? []).find(
        (f) => f.name.toLowerCase() === OTP_FIELD,
      ) ?? null,
    [formData.custom_fields],
  );

  const [editing, setEditing] = useState<boolean>(!otpField);
  const [input, setInput] = useState<string>(otpField?.value ?? "");
  const [preview, setPreview] = useState<TotpPreview | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [validating, setValidating] = useState(false);
  const [copied, setCopied] = useState(false);
  const [tick, setTick] = useState(0);

  // Re-open the editor if the entry switches and there's no otp field yet.
  useEffect(() => {
    setEditing(!otpField);
    setInput(otpField?.value ?? "");
    setError(null);
    setPreview(null);
  }, [otpField?.value, formData.uuid]);

  // Live-validate the input. Debounced 200 ms so we don't hammer the IPC
  // while the user types/pastes.
  useEffect(() => {
    if (!editing) return;
    if (!input.trim()) {
      setPreview(null);
      setError(null);
      return;
    }
    const t = setTimeout(async () => {
      setValidating(true);
      try {
        const result = await previewTotp(input);
        setPreview(result);
        setError(null);
      } catch (e) {
        setPreview(null);
        setError(String(e));
      } finally {
        setValidating(false);
      }
    }, 200);
    return () => clearTimeout(t);
  }, [input, editing]);

  // 1 Hz ticker so the displayed code/countdown refresh.
  const showingCode = !editing && otpField;
  useEffect(() => {
    if (!showingCode) return;
    const t = setInterval(() => setTick((n) => n + 1), 1000);
    return () => clearInterval(t);
  }, [showingCode]);

  // When showing a saved otp, fetch its current code from the backend.
  const [savedCode, setSavedCode] = useState<TotpPreview | null>(null);
  useEffect(() => {
    if (editing) return;
    if (!otpField) return;
    previewTotp(otpField.value)
      .then(setSavedCode)
      .catch(() => setSavedCode(null));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [editing, otpField?.value, tick]);

  function commit(uri: string) {
    setFormData((prev) => {
      const others = (prev.custom_fields ?? []).filter(
        (f) => f.name.toLowerCase() !== OTP_FIELD,
      );
      const next: CustomField = {
        name: OTP_FIELD,
        value: uri,
        protected: true,
      };
      return { ...prev, custom_fields: [...others, next] };
    });
    setHasChanges(true);
    setEditing(false);
  }

  function remove() {
    setFormData((prev) => ({
      ...prev,
      custom_fields: (prev.custom_fields ?? []).filter(
        (f) => f.name.toLowerCase() !== OTP_FIELD,
      ),
    }));
    setHasChanges(true);
    setEditing(true);
    setInput("");
    setPreview(null);
    setError(null);
  }

  async function copyCode() {
    const code = savedCode?.code ?? preview?.code;
    if (!code) return;
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1200);
  }

  return (
    <div className="rounded-md border bg-card p-3 space-y-2">
      <div className="flex items-center gap-2">
        <KeyRound className="h-4 w-4 text-muted-foreground" />
        <Label className="text-sm font-medium">Two-factor authentication (TOTP)</Label>
      </div>

      {!editing && otpField && savedCode && (
        <SavedCodeView
          code={savedCode.code}
          remaining={Math.max(
            0,
            Math.ceil((savedCode.remaining_seconds * 1000 - tick * 0) / 1000),
          )}
          period={savedCode.period}
          copied={copied}
          onCopy={copyCode}
          onReconfigure={() => setEditing(true)}
          onRemove={remove}
        />
      )}

      {!editing && otpField && !savedCode && (
        <p className="text-xs text-muted-foreground">Reading current code…</p>
      )}

      {editing && (
        <div className="space-y-2">
          <p className="text-xs text-muted-foreground leading-relaxed">
            Paste an <code className="font-mono">otpauth://</code> URI from
            the site&apos;s 2FA setup screen, or just the secret you got from
            the QR-code &quot;manual entry&quot; option.
          </p>
          <div className="flex items-stretch gap-1">
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="otpauth://totp/... or JBSWY3DPEHPK3PXP"
              className="font-mono text-xs"
              spellCheck={false}
            />
            <Button
              size="sm"
              onClick={() => preview && commit(preview.otpauth_uri)}
              disabled={!preview || validating}
            >
              Save 2FA
            </Button>
            {otpField && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  setEditing(false);
                  setInput(otpField.value);
                  setError(null);
                }}
              >
                Cancel
              </Button>
            )}
          </div>

          {preview && (
            <div className="flex items-center justify-between rounded border border-emerald-500/30 bg-emerald-500/5 px-2.5 py-2">
              <div className="flex items-center gap-2 text-xs">
                <span className="text-emerald-600 dark:text-emerald-400 font-medium">
                  Looks good:
                </span>
                <span className="font-mono text-base tracking-widest">
                  {preview.code.slice(0, 3)} {preview.code.slice(3)}
                </span>
                <span className="text-muted-foreground">
                  · refreshes in {preview.remaining_seconds}s
                </span>
              </div>
            </div>
          )}

          {error && (
            <p className="text-xs text-rose-600 dark:text-rose-400">
              Not valid: {error}
            </p>
          )}

          {validating && !preview && !error && (
            <p className="text-xs text-muted-foreground">Validating…</p>
          )}
        </div>
      )}
    </div>
  );
}

function SavedCodeView(props: {
  code: string;
  remaining: number;
  period: number;
  copied: boolean;
  onCopy: () => void;
  onReconfigure: () => void;
  onRemove: () => void;
}) {
  const ratio = props.period > 0 ? props.remaining / props.period : 0;
  const urgent = props.remaining <= 5;
  return (
    <div className="flex items-center gap-3">
      <div className="flex flex-1 items-center justify-between rounded-md border bg-background px-3 py-2">
        <span className="font-mono text-lg tracking-widest tabular-nums">
          {props.code.slice(0, 3)} {props.code.slice(3)}
        </span>
        <CountdownRing ratio={ratio} urgent={urgent} label={String(props.remaining)} />
      </div>
      <Button size="sm" variant="outline" onClick={props.onCopy}>
        {props.copied ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}
      </Button>
      <Button size="sm" variant="outline" onClick={props.onReconfigure}>
        Reconfigure
      </Button>
      <Button size="sm" variant="ghost" onClick={props.onRemove} title="Remove 2FA">
        <Trash2 className="h-3.5 w-3.5 text-rose-600" />
      </Button>
    </div>
  );
}

function CountdownRing(props: { ratio: number; urgent: boolean; label: string }) {
  const radius = 10;
  const circumference = 2 * Math.PI * radius;
  const dash = circumference * Math.max(0, Math.min(1, props.ratio));
  return (
    <div className="relative h-6 w-6">
      <svg viewBox="0 0 24 24" className="h-6 w-6 -rotate-90">
        <circle
          cx="12"
          cy="12"
          r={radius}
          stroke="currentColor"
          className="text-border"
          strokeWidth="2"
          fill="none"
        />
        <circle
          cx="12"
          cy="12"
          r={radius}
          stroke="currentColor"
          className={props.urgent ? "text-rose-500" : "text-primary"}
          strokeWidth="2"
          strokeDasharray={`${dash} ${circumference - dash}`}
          strokeLinecap="round"
          fill="none"
        />
      </svg>
      <span
        className={
          "absolute inset-0 flex items-center justify-center text-[10px] font-medium tabular-nums " +
          (props.urgent ? "text-rose-600" : "")
        }
      >
        {props.label}
      </span>
    </div>
  );
}

// src/lib/components/TotpSection.svelte
<script lang="ts">
  import { Button, Input, Label } from "$lib/ui";
  import { Check, Copy, KeyRound, Trash2 } from "@lucide/svelte";
  import { previewTotp, type TotpPreview, type EntryData, type CustomField } from "$lib/tauri";
  import { writeText } from "@tauri-apps/plugin-clipboard-manager";

  type Props = {
    formData: EntryData;
    onUpdate: (next: EntryData) => void;
  };

  let { formData, onUpdate }: Props = $props();

  const OTP_FIELD = "otp";
  const otpField = $derived(
    (formData.custom_fields ?? []).find((f) => f.name.toLowerCase() === OTP_FIELD) ?? null,
  );

  // svelte-ignore state_referenced_locally
  let editing = $state(!otpField);
  // svelte-ignore state_referenced_locally
  let input = $state(otpField?.value ?? "");
  let preview = $state<TotpPreview | null>(null);
  let error = $state<string | null>(null);
  let validating = $state(false);
  let copied = $state(false);
  let tick = $state(0);
  let savedCode = $state<TotpPreview | null>(null);

  $effect(() => {
    editing = !otpField;
    input = otpField?.value ?? "";
    error = null;
    preview = null;
  });

  $effect(() => {
    if (!editing) return;
    if (!input.trim()) {
      preview = null;
      error = null;
      return;
    }
    const t = setTimeout(async () => {
      validating = true;
      try {
        const r = await previewTotp(input);
        preview = r;
        error = null;
      } catch (e) {
        preview = null;
        error = String(e);
      } finally {
        validating = false;
      }
    }, 200);
    return () => clearTimeout(t);
  });

  $effect(() => {
    const showing = !editing && otpField;
    if (!showing) return;
    const t = setInterval(() => (tick += 1), 1000);
    return () => clearInterval(t);
  });

  $effect(() => {
    if (editing || !otpField) return;
    // re-evaluate every tick
    void tick;
    previewTotp(otpField.value).then((r) => (savedCode = r)).catch(() => (savedCode = null));
  });

  function commit(uri: string) {
    const others = (formData.custom_fields ?? []).filter((f) => f.name.toLowerCase() !== OTP_FIELD);
    const next: CustomField = { name: OTP_FIELD, value: uri, protected: true };
    onUpdate({ ...formData, custom_fields: [...others, next] });
    editing = false;
  }

  function remove() {
    onUpdate({
      ...formData,
      custom_fields: (formData.custom_fields ?? []).filter((f) => f.name.toLowerCase() !== OTP_FIELD),
    });
    editing = true;
    input = "";
    preview = null;
    error = null;
  }

  async function copyCode() {
    const code = savedCode?.code ?? preview?.code;
    if (!code) return;
    await writeText(code);
    copied = true;
    setTimeout(() => (copied = false), 1200);
  }
</script>

<div class="rounded-md border bg-card p-3 space-y-2">
  <div class="flex items-center gap-2">
    <KeyRound class="h-4 w-4 text-muted-foreground" />
    <Label class="text-sm font-medium">Two-factor authentication (TOTP)</Label>
  </div>

  {#if !editing && otpField && savedCode}
    {@const ratio = savedCode.period > 0 ? savedCode.remaining_seconds / savedCode.period : 0}
    {@const urgent = savedCode.remaining_seconds <= 5}
    <div class="flex items-center gap-3">
      <div class="flex flex-1 items-center justify-between rounded-md border bg-background px-3 py-2">
        <span class="font-mono text-lg tracking-widest tabular-nums">
          {savedCode.code.slice(0, 3)} {savedCode.code.slice(3)}
        </span>
        <div class="relative h-6 w-6">
          <svg viewBox="0 0 24 24" class="h-6 w-6 -rotate-90">
            <circle cx="12" cy="12" r="10" stroke="currentColor" class="text-border" stroke-width="2" fill="none" />
            <circle
              cx="12"
              cy="12"
              r="10"
              stroke="currentColor"
              class={urgent ? "text-destructive" : "text-primary"}
              stroke-width="2"
              stroke-dasharray="{2 * Math.PI * 10 * Math.max(0, Math.min(1, ratio))} {2 * Math.PI * 10 - 2 * Math.PI * 10 * Math.max(0, Math.min(1, ratio))}"
              stroke-linecap="round"
              fill="none"
            />
          </svg>
          <span class="absolute inset-0 flex items-center justify-center text-[10px] font-medium tabular-nums {urgent ? 'text-destructive' : ''}">
            {savedCode.remaining_seconds}
          </span>
        </div>
      </div>
      <Button size="sm" variant="outline" onclick={copyCode}>
        {#if copied}<Check class="h-3.5 w-3.5" />{:else}<Copy class="h-3.5 w-3.5" />{/if}
      </Button>
      <Button size="sm" variant="outline" onclick={() => (editing = true)}>Reconfigure</Button>
      <Button size="sm" variant="ghost" onclick={remove} title="Remove 2FA">
        <Trash2 class="h-3.5 w-3.5 text-destructive" />
      </Button>
    </div>
  {:else if !editing && otpField && !savedCode}
    <p class="text-xs text-muted-foreground">Reading current code…</p>
  {/if}

  {#if editing}
    <div class="space-y-2">
      <p class="text-xs text-muted-foreground leading-relaxed">
        Paste an <code class="font-mono">otpauth://</code> URI from the site's 2FA setup screen, or the secret string.
      </p>
      <div class="flex items-stretch gap-1">
        <Input
          bind:value={input}
          placeholder="otpauth://totp/... or JBSWY3DPEHPK3PXP"
          class="font-mono text-xs"
          spellcheck={false}
        />
        <Button size="sm" onclick={() => preview && commit(preview.otpauth_uri)} disabled={!preview || validating}>
          Save 2FA
        </Button>
        {#if otpField}
          <Button size="sm" variant="outline" onclick={() => { editing = false; input = otpField.value; error = null; }}>
            Cancel
          </Button>
        {/if}
      </div>

      {#if preview}
        <div class="flex items-center justify-between rounded border border-success/30 bg-success/5 px-2.5 py-2">
          <div class="flex items-center gap-2 text-xs">
            <span class="text-success font-medium">Looks good:</span>
            <span class="font-mono text-base tracking-widest">{preview.code.slice(0, 3)} {preview.code.slice(3)}</span>
            <span class="text-muted-foreground">· refreshes in {preview.remaining_seconds}s</span>
          </div>
        </div>
      {/if}

      {#if error}
        <p class="text-xs text-destructive">Not valid: {error}</p>
      {/if}
      {#if validating && !preview && !error}
        <p class="text-xs text-muted-foreground">Validating…</p>
      {/if}
    </div>
  {/if}
</div>
